//quarkus.tls.trust-all=true
//quarkus.http.ssl.client-auth=request
//quarkus.http.ssl.certificate.trust-store-file=server-truststore.jks
//quarkus.oidc.certificate-chain.trust-store-file=server-truststore.jks
//quarkus.tls.trust-store.jks.path=server-truststore.jks
//quarkus.http.ssl.certificate.trust-store-password =secret
//quarkus.oidc.certificate-chain.trust-store-password=secret
//quarkus.tls.trust-store.jks.password =secret
//quarkus.http.ssl.certificate.trust-store-cert-alias=server
//quarkus.oidc.certificate-chain.trust-store-cert-alias=server
//quarkus.tls.trust-store.jks.alias=server
//quarkus.log.level=DEBUG
//quarkus.tls.trust-store.pem.certs=/server-ca.crt

