name: "Release check"
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/project.yml
jobs:
  check-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check release version
        run: |
          releases=$(curl -sSL "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")
          next_release=$(grep -E 'current-version:\s*' .github/project.yml | awk '{print $2}')
          
          branch_version=$(echo "$GITHUB_BASE_REF" | cut -d. -f1,2)
          latest_branch_tag_patch_version=$(echo "$releases" | jq -r --arg version "$branch_version" '
            .[] 
            | select(.tag_name | contains($version)) 
            | .tag_name' | grep -v "Beta" | head -1 | cut -d. -f3)
          
          branch_minor_version=$(echo "$GITHUB_BASE_REF" | cut -d. -f2,2)
          next_release_minor_version=$(echo "$next_release" | cut -d"." -f2,2)
          next_release_patch_version=$(echo "$next_release" | cut -d"." -f3,3)
          beta_tag_exists=$(echo "$next_release" | cut -d"." -f4,4 || true)
          
          if [ -n "$beta_tag_exists" ]; then
            echo "Error: releases cannot consist any qualifier after version"
            exit 1;
          fi

          if [[ "$branch_minor_version" != "$next_release_minor_version" ]]; then
            echo "Error: minor versions cannot be changed"
            exit 1;
          fi
          
          if [[ $(("$latest_branch_tag_patch_version" + 1)) != "$next_release_patch_version" ]]; then
            echo "Error: release patch versions should be bumped one by one as sequence"
            exit 1;
          fi
          
          project_next_version=$(grep -E 'next-version:\s*' .github/project.yml | awk '{print $2}')
          project_next_base=$(echo "$project_next_version" | cut -d"." -f1,2)
          
          project_current_patch_version="$next_release_patch_version"
          project_next_patch_version=$(echo "$project_next_version" | awk -F. '{print $3}')
          
          if [[ "$branch_version" != "$project_next_base" ]] || [[ $(("$project_current_patch_version" + 1)) != "$project_next_patch_version" ]]; then
            echo "Error: the next-version in project.yaml is not valid. Patch version of the next release must be one upper than the latest"
            exit 1;
          fi
