name: "PR"
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  linux-build-jvm-latest:
    name: Linux - JVM build - Latest Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        quarkus-version: ["3.2.999-SNAPSHOT"]
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'maven'
      - name: Build Quarkus CLI
        run: |
          git clone https://github.com/quarkusio/quarkus.git && cd quarkus/devtools/cli && git checkout 3.2 && mvn -B -s ../../../.github/mvn-settings.xml clean install -Dquickly -Dno-test-modules -Prelocations
      - name: Install Quarkus CLI
        run: |
          cat <<EOF > ./quarkus-dev-cli
          #!/bin/bash
          java -jar $PWD/quarkus/devtools/cli/target/quarkus-cli-3.2.999-SNAPSHOT-runner.jar "\$@"
          EOF
          chmod +x ./quarkus-dev-cli
          ./quarkus-dev-cli version
      - name: Build in JVM mode
        run: |
          ./quarkus-dev-cli "--version" "-Dquarkus.analytics.disabled=true"
          ./quarkus-dev-cli "-v" "-Dquarkus.analytics.disabled=true"
          ${PWD}/quarkus-dev-cli "--version" "-Dquarkus.analytics.disabled=true"
          ${PWD}/quarkus-dev-cli "-v" "-Dquarkus.analytics.disabled=true"
          //mvn -B -fae -s .github/mvn-settings.xml clean install -Pframework,examples,extensions -Drun-cli-tests -pl quarkus-test-cli -Dts.quarkus.cli.cmd="${PWD}/quarkus-dev-cli" -Dquarkus.platform.version="${{ matrix.quarkus-version }}"
      - name: Zip Artifacts
        run: |
          zip -R artifacts-latest-linux-jvm${{ matrix.java }}.zip '*-reports/*'
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ci-artifacts
          path: artifacts-latest-linux-jvm${{ matrix.java }}.zip